sudo: required

language: node_js
node_js:
  - "6.11.0"

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t microcks/microcks-postman-runtime .;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push microcks/microcks-postman-runtime:latest;
    docker tag microcks/microcks-postman-runtime:latest quay.io/microcks/microcks-postman-runtime:latest;
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/microcks/microcks-postman-runtime:latest;
    fi
  - if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then
    docker build -t microcks/microcks-postman-runtime .;
    docker tag microcks/microcks-postman-runtime microcks/microcks-postman-runtime:$TRAVIS_TAG;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push microcks/microcks-postman-runtime:$TRAVIS_TAG;
    docker tag microcks/microcks-postman-runtime:$TRAVIS_TAG quay.io/microcks/microcks-postman-runtime:$TRAVIS_TAG;
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/microcks/microcks-postman-runtime:$TRAVIS_TAG;
    fi
